global using System;
global using System.Threading.Tasks;
global using System.Security.Claims;
global using System.Numerics;
global using System.Drawing;

global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.ClearScript;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.AspNetCore.Authorization;
global using Serilog;
global using Serilog.Core;
global using Serilog.Events;
global using Newtonsoft.Json;

global using Realm.Interfaces.Extend;
global using Realm.Persistance.Scripting.Classes;
global using Realm.Scripting.Interfaces;
global using Realm.Persistance.Data;
global using Realm.Scripting.Extensions;
global using Realm.Interfaces.Server.Services;
global using Realm.Persistance.Extensions;
global using Realm.Persistance.Interfaces;
global using Realm.Configuration;
global using Realm.Persistance.Services;
global using Realm.Persistance.Logger.Enrichers;
