global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Numerics;
global using System.Threading.Tasks;
global using System.Reflection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Configuration;
global using Serilog;

global using SlipeServer.Server.Elements;
global using SlipeServer.Server;
global using SlipeServer.Server.ServerBuilders;
global using SlipeServer.Server.Resources.Providers;
global using SlipeServer.Server.Resources;
global using SlipeServer.Packets.Lua.Camera;
global using SlipeServer.Server.Elements.Events;
global using SlipeServer.Server.Events;
global using SlipeServer.Packets.Definitions.Lua;
global using SlipeServer.Server.ElementCollections;
global using SlipeServer.Server.Mappers;
global using SlipeServerConfiguration = SlipeServer.Server.Configuration;

global using Realm.Persistance;
global using Realm.Persistance.Repositories.Interfaces;
global using Realm.Persistance.SQLite;
global using Realm.Scripting.Extensions;
global using Realm.Server.Commands;
global using Realm.Discord;
global using Realm.Interfaces;
global using Realm.Server.Gui;
global using Realm.Interfaces.Server;
global using Realm.Interfaces.Common;
global using Realm.Interfaces.Scripting.Classes;
global using Realm.Scripting.Classes;
global using Realm.Server.Managers;
global using Realm.Server.ResourcesLogic;
global using Realm.Interfaces.Scripting;
global using Realm.Server.Extensions;
global using Realm.Configuration.Configurations;
global using Realm.Common.Extensions;
global using Realm.Interfaces.Server.Identity;
global using Realm.Server.Identity;

global using ConfigurationProvider = Realm.Configuration.ConfigurationProvider;
