global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Numerics;
global using System.Threading.Tasks;
global using System.Security.Claims;
global using Microsoft.Extensions.Hosting;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Configuration;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.ClearScript;
global using Microsoft.AspNetCore.Authorization;
global using Serilog;
global using Serilog.Core;
global using Serilog.Events;

global using SlipeServer.Server.Elements;
global using SlipeServer.Server;
global using SlipeServer.Server.ServerBuilders;
global using SlipeServer.Server.Resources.Providers;
global using SlipeServer.Server.Resources;
global using SlipeServer.Packets.Lua.Camera;
global using SlipeServer.Server.Elements.Events;
global using SlipeServer.Server.Events;
global using SlipeServer.Packets.Definitions.Lua;
global using SlipeServer.Server.ElementCollections;
global using SlipeServer.Server.Mappers;
global using SlipeServerConfiguration = SlipeServer.Server.Configuration;

global using Realm.Persistance;
global using Realm.Persistance.SQLite;
global using Realm.Server.Commands;
global using Realm.Interfaces.Server;
global using Realm.Interfaces.Common;
global using Realm.Server.ResourcesLogic;
global using Realm.Server.Extensions;
global using Realm.Configuration.Configurations;
global using Realm.Interfaces.Extend;
global using Realm.Scripting.Scopes;
global using Realm.Server.Elements;
global using Realm.Scripting.Interfaces;
global using Realm.Server.Interfaces;
global using Realm.Scripting.Extensions;
global using Realm.Scripting.Classes;
global using Realm.Server.Scripting.Events;
global using Realm.Persistance.Data;
global using Realm.Persistance.Scripting.Classes;

global using Realm.Resources.AgnosticGuiSystem;

global using ConfigurationProvider = Realm.Configuration.ConfigurationProvider;
