global using System;
global using System.Linq;
global using System.Threading.Tasks;
global using RealmCore.Module.Discord.Interfaces;
global using RealmCore.Server.Interfaces;
global using SlipeServer.Server.Services;
global using Microsoft.Extensions.Logging;
global using RealmCore.Server.Elements;
global using SlipeServer.Server.ElementCollections;
