global using SlipeServer.Server.Elements;
global using System.Drawing;
global using System.Numerics;
global using Vehicle = SlipeServer.Server.Elements.Vehicle;
global using Newtonsoft.Json;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.DependencyInjection;
global using Realm.Persistance.Data;
global using System.Security.Claims;
global using Realm.Domain.Components.Common;
global using Realm.Domain.Components.Elements;
global using Realm.Resources.AgnosticGuiSystem;
global using SlipeServer.Server.Mappers;
global using Realm.Domain.Extensions;
global using System.Linq.Expressions;
global using SlipeServer.Packets.Definitions.Lua;
global using System.Reflection;
global using Realm.Domain.Components.Players;
global using Realm.Resources.ClientInterface;
global using Realm.Resources.Overlay;
global using SlipeServer.Packets.Lua.Camera;
global using SlipeServer.Server.Elements.Enums;
global using SlipeServer.Server.Services;
global using SlipeServer.Packets.Enums;
global using Realm.Persistance.Data.Helpers;
global using SlipeServer.Server.Elements.Events;
global using Realm.Common.Exceptions;
global using Realm.Domain.Registries;
global using Realm.Domain.Inventory;
global using Microsoft.AspNetCore.Components;
global using Realm.Domain.Exceptions;
global using Realm.Domain.Interfaces;
global using SlipeServer.Server.Elements.ColShapes;
global using SlipeServer.Server.Events;
global using SlipeServer.Server.Constants;
global using SlipeServer.Resources.Text3d;
global using System.Runtime.CompilerServices;
global using Microsoft.Extensions.Logging;
global using Realm.Domain.Attributes;
global using Realm.Domain.Concepts.Objectives;
global using Realm.Domain.Components.Elements.CollisionShapes;
global using Realm.Domain.Components.Object;
global using System.Globalization;
global using Realm.Common.Providers;
global using Realm.Domain.Enums;
global using Realm.Domain.IdGenerators;
global using SlipeServer.Server.Clients;
global using SlipeServer.Server.Collections;
global using SlipeServer.Server.Concepts;

[assembly: InternalsVisibleTo("Realm.Server")]
[assembly: InternalsVisibleTo("Realm.Tests")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]