global using SlipeServer.Server.Elements;
global using System.Drawing;
global using System.Numerics;
global using Vehicle = SlipeServer.Server.Elements.Vehicle;
global using Newtonsoft.Json;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.DependencyInjection;
global using Realm.Resources.StatisticsCounter;
global using Realm.Persistance.Data;
global using System.Security.Claims;
global using Realm.Interfaces.Server;
global using Realm.Domain.Components.Common;