global using SlipeServer.Server.Elements;
global using System.Drawing;
global using System.Numerics;
global using Serilog;
global using Vehicle = SlipeServer.Server.Elements.Vehicle;
global using Newtonsoft.Json;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.DependencyInjection;
global using Realm.Resources.StatisticsCounter;
global using Realm.Persistance.Data;
global using System.Security.Claims;
global using Realm.Interfaces.Server;
global using Realm.Domain.Components.Common;
global using Realm.Domain.Components.Elements;
global using Realm.Resources.AgnosticGuiSystem;
global using SlipeServer.Server.Mappers;
global using Realm.Domain.Extensions;
global using System.Linq.Expressions;
global using SlipeServer.Packets.Definitions.Lua;
global using System.Reflection;
global using Realm.Domain.Components.Players;
global using Realm.Resources.ClientInterface;
global using Realm.Resources.Overlay;
global using SlipeServer.Packets.Lua.Camera;
global using SlipeServer.Server.Elements.Enums;
global using SlipeServer.Server.Services;
global using SlipeServer.Packets.Enums;
global using Realm.Persistance.Data.Helpers;
global using SlipeServer.Server.Elements.Events;
global using Realm.Common.Exceptions;
global using Realm.Configuration;
global using Realm.Domain.Registries;
global using Realm.Domain.Inventory;
global using InventoryData = Realm.Persistance.Data.Inventory;
global using Microsoft.AspNetCore.Components;
global using Realm.Assets.Factories;
global using Realm.Resources.Assets;
global using Realm.Domain.Exceptions;
global using Realm.Domain.Interfaces;
global using SlipeServer.Server.Elements.ColShapes;
global using Realm.Domain.Persistance;
global using Realm.Resources.AFK;
global using Realm.Domain.Contextes;
global using SlipeServer.Server.Events;
global using SlipeServer.Server.Constants;
global using SlipeServer.Resources.Text3d;
global using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Realm.Server")]
[assembly: InternalsVisibleTo("Realm.Tests")]