// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealmCore.SQLite;

#nullable disable

namespace RealmCore.Persistence.SQLite.Migrations
{
    [DbContext(typeof(SQLiteDb))]
    [Migration("20230716044628_RatingAndOpinionsTable")]
    partial class RatingAndOpinionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.AchievementData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AchievementId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PrizeReceived")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Progress")
                        .HasColumnType("REAL");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "AchievementId");

                    b.ToTable("Achievements", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.BanData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsible")
                        .HasColumnType("TEXT");

                    b.Property<string>("Serial")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bans", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.DailyVisitsData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastVisit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("VisitsInRow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitsInRowRecord")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("DailyVisits", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.DiscordIntegrationData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("DiscordIntegrations", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.DiscoveryData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscoveryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "DiscoveryId");

                    b.ToTable("Discoveries", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.FractionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Fractions", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.FractionMemberData", b =>
                {
                    b.Property<int>("FractionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("FractionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FractionMembers", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.GroupData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Shortcut")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Shortcut")
                        .IsUnique();

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.GroupMemberData", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.InventoryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Size")
                        .HasPrecision(38, 18)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inventories", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.InventoryItemData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.JobStatisticsData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<ulong>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TimePlayed")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "JobId", "Date");

                    b.ToTable("JobPoints", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.JobUpgradeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "JobId", "UpgradeId");

                    b.ToTable("JobUpgrades", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.OpinionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opinion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OpinionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Opinions", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.RatingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.RoleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogindDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSerial")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTransformAndMotion")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<uint>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Money")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nick")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PlayTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterSerial")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegisteredDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<short>("Skin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserInventoryData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("UserInventories", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserLicenseData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LicenseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspendedReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SuspendedUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LicenseId");

                    b.ToTable("UserLicenses", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserRewardData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RewardId");

                    b.ToTable("UserRewards", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserSettingData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SettingId")
                        .HasMaxLength(255)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "SettingId");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserStatData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("UserId", "StatId");

                    b.ToTable("UserStats", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserUpgradeData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "UpgradeId");

                    b.ToTable("UserUpgrades", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserWhitelistedSerialData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Serial")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "Serial");

                    b.ToTable("UserWhitelistedSerials", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"Color1\":\"White\",\"Color2\":\"White\",\"Color3\":\"White\",\"Color4\":\"White\",\"HeadLightColor\":\"White\"}");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"FrontLeftPanel\":0,\"FrontRightPanel\":0,\"RearLeftPanel\":0,\"RearRightPanel\":0,\"Windscreen\":0,\"FrontBumper\":0,\"RearBumper\":0,\"Hood\":0,\"Trunk\":0,\"FrontLeftDoor\":0,\"FrontRightDoor\":0,\"RearLeftDoor\":0,\"RearRightDoor\":0,\"FrontLeftLight\":0,\"FrontRightLight\":0,\"RearRightLight\":0,\"RearLeftLight\":0}");

                    b.Property<string>("DoorOpenRatio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"Hood\":0.0,\"Trunk\":0.0,\"FrontLeft\":0.0,\"FrontRight\":0.0,\"RearLeft\":0.0,\"RearRight\":0.0}");

                    b.Property<bool>("EngineState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<float>("Health")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1000f);

                    b.Property<bool>("IsFrozen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<byte>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LandingGearDown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("Locked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<float>("Mileage")
                        .HasColumnType("REAL");

                    b.Property<ushort>("Model")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("OverrideLights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<short>("Paintjob")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((short)3);

                    b.Property<string>("Platetext")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Removed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("SirensState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("Spawned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("TaxiLightState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("TransformAndMotion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"Position\":{\"X\":0.0,\"Y\":0.0,\"Z\":0.0},\"Rotation\":{\"X\":0.0,\"Y\":0.0,\"Z\":0.0},\"Interior\":0,\"Dimension\":0,\"Velocity\":{\"X\":0.0,\"Y\":0.0,\"Z\":0.0},\"AngularVelocity\":{\"X\":0.0,\"Y\":0.0,\"Z\":0.0}}");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"Variant1\":255,\"Variant2\":255}");

                    b.Property<string>("WheelStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"FrontLeft\":0,\"RearLeft\":0,\"FrontRight\":0,\"RearRight\":0}");

                    b.HasKey("Id");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleEngineData", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("EngineId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId", "EngineId");

                    b.ToTable("VehicleEngines", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleEventData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleEvents", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleFuelData", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("FuelType")
                        .HasMaxLength(16)
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<float>("FuelConsumptionPerOneKm")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxCapacity")
                        .HasColumnType("REAL");

                    b.Property<float>("MinimumDistanceThreshold")
                        .HasColumnType("REAL");

                    b.HasKey("VehicleId", "FuelType");

                    b.ToTable("VehicleFuels", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleInventoryData", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("VehicleInventories", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehiclePartDamageData", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("State")
                        .HasColumnType("REAL");

                    b.HasKey("VehicleId", "PartId");

                    b.ToTable("VehiclePartDamages", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleUpgradeData", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId", "UpgradeId");

                    b.ToTable("VehicleUpgrades", (string)null);
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleUserAccessData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AccessType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomValue")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleUserAccess", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.RoleData", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.RoleData", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.AchievementData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.BanData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.DailyVisitsData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithOne("DailyVisits")
                        .HasForeignKey("RealmCore.Persistence.Data.DailyVisitsData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.DiscordIntegrationData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", "User")
                        .WithOne("DiscordIntegration")
                        .HasForeignKey("RealmCore.Persistence.Data.DiscordIntegrationData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.DiscoveryData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany("Discoveries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.FractionMemberData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.FractionData", "Fraction")
                        .WithMany("Members")
                        .HasForeignKey("FractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmCore.Persistence.Data.UserData", "User")
                        .WithMany("FractionMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fraction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.GroupMemberData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.GroupData", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmCore.Persistence.Data.UserData", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.InventoryItemData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.InventoryData", "Inventory")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.JobStatisticsData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany("JobStatistics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.JobUpgradeData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany("JobUpgrades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.OpinionData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", "User")
                        .WithMany("Opinions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.RatingData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserInventoryData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.InventoryData", "Inventory")
                        .WithMany("UserInventories")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmCore.Persistence.Data.UserData", "User")
                        .WithMany("UserInventories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserLicenseData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany("Licenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserRewardData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany("Rewards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserSettingData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany("Settings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserStatData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany("Stats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserUpgradeData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany("Upgrades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserWhitelistedSerialData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", null)
                        .WithMany("WhitelistedSerials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleEngineData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.VehicleData", null)
                        .WithMany("VehicleEngines")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleEventData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.VehicleData", null)
                        .WithMany("VehicleEvents")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleFuelData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.VehicleData", null)
                        .WithMany("Fuels")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleInventoryData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.InventoryData", "Inventory")
                        .WithMany("VehicleInventories")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmCore.Persistence.Data.VehicleData", "Vehicle")
                        .WithMany("VehicleInventories")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehiclePartDamageData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.VehicleData", null)
                        .WithMany("PartDamages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleUpgradeData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.VehicleData", null)
                        .WithMany("Upgrades")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleUserAccessData", b =>
                {
                    b.HasOne("RealmCore.Persistence.Data.UserData", "User")
                        .WithMany("VehicleUserAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmCore.Persistence.Data.VehicleData", "Vehicle")
                        .WithMany("UserAccesses")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.FractionData", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.GroupData", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.InventoryData", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("UserInventories");

                    b.Navigation("VehicleInventories");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.UserData", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("DailyVisits");

                    b.Navigation("DiscordIntegration");

                    b.Navigation("Discoveries");

                    b.Navigation("FractionMembers");

                    b.Navigation("GroupMembers");

                    b.Navigation("JobStatistics");

                    b.Navigation("JobUpgrades");

                    b.Navigation("Licenses");

                    b.Navigation("Opinions");

                    b.Navigation("Ratings");

                    b.Navigation("Rewards");

                    b.Navigation("Settings");

                    b.Navigation("Stats");

                    b.Navigation("Upgrades");

                    b.Navigation("UserInventories");

                    b.Navigation("VehicleUserAccesses");

                    b.Navigation("WhitelistedSerials");
                });

            modelBuilder.Entity("RealmCore.Persistence.Data.VehicleData", b =>
                {
                    b.Navigation("Fuels");

                    b.Navigation("PartDamages");

                    b.Navigation("Upgrades");

                    b.Navigation("UserAccesses");

                    b.Navigation("VehicleEngines");

                    b.Navigation("VehicleEvents");

                    b.Navigation("VehicleInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
