name: Push nuget


on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '5.x'
    - run: nuget pack src/Realm.Server/Realm.Server.csproj -Build -IncludeReferencedProjects -OutputFileNamesWithoutVersion -Version ${{github.ref_name}}
    - run: nuget push MTARealm.Server.nupkg