name: Publish to nuget
on:
  push:
    branches:
      - main
      
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Realm.Server/Realm.Server.csproj
          BUILD_CONFIGURATION: Release
          PACKAGE_NAME: RPGRealm.Server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}